<?php
require_once __DIR__ . '/../config/app.php';
require_module_access('admin');
ensure_destination_visit_schema();

$pageTitle='Assign Existing Customers';
$breadcrumbs=[['label'=>'Home','url'=>app_url('index.php')],['label'=>'Admin','url'=>app_url('admin.php')],['label'=>'Assign Existing Customers']];
$internalBackUrl=requested_return_url(app_url('marketing.php?view=setup'));
$message=$error='';
$locationId=max(0,(int)($_GET['location_id']??0));
$destinationId=max(0,(int)($_GET['destination_id']??0));

if($_SERVER['REQUEST_METHOD']==='POST'){
    $vendorId=max(0,(int)($_POST['vendor_id']??0));
    $selectedRecords=array_values(array_unique(array_map('strval',(array)($_POST['customer_records']??[]))));
    $legacyVisitIds=[];$normalizedCustomerIds=[];
    foreach($selectedRecords as $selectedRecord){if(!preg_match('/^(legacy|normalized):(\d+)$/',$selectedRecord,$match))continue;$id=(int)$match[2];if($id<=0)continue;if($match[1]==='legacy')$legacyVisitIds[]=$id;else $normalizedCustomerIds[]=$id;}
    $legacyVisitIds=array_values(array_unique($legacyVisitIds));$normalizedCustomerIds=array_values(array_unique($normalizedCustomerIds));
    if(!verify_csrf_token((string)($_POST['csrf_token']??'')))$error='Your session expired. Please try again.';
    elseif(!$legacyVisitIds&&!$normalizedCustomerIds)$error='Select at least one customer.';
    else{$vendorCheck=db()->prepare('SELECT COUNT(*) FROM vendors WHERE id=? AND is_active=1');$vendorCheck->execute([$vendorId]);if(!$vendorId||!(int)$vendorCheck->fetchColumn())$error='Select a valid active vendor.';}
    if($error===''){db()->beginTransaction();try{$assignedCount=0;
        if($legacyVisitIds){$marks=implode(',',array_fill(0,count($legacyVisitIds),'?'));$update=db()->prepare("UPDATE destination_visits SET vendor_id=? WHERE vendor_id IS NULL AND visit_type='registration' AND id IN ($marks)");$update->execute([$vendorId,...$legacyVisitIds]);$assignedCount+=$update->rowCount();}
        if($normalizedCustomerIds){$marks=implode(',',array_fill(0,count($normalizedCustomerIds),'?'));$updateCustomers=db()->prepare("UPDATE customers SET vendor_id=? WHERE vendor_id IS NULL AND id IN ($marks)");$updateCustomers->execute([$vendorId,...$normalizedCustomerIds]);$assignedCount+=$updateCustomers->rowCount();$updateVisits=db()->prepare("UPDATE visits SET vendor_id=? WHERE vendor_id IS NULL AND customer_id IN ($marks)");$updateVisits->execute([$vendorId,...$normalizedCustomerIds]);}
        db()->commit();$message=number_format($assignedCount).' customer'.($assignedCount===1?' was':'s were').' assigned to the vendor.';
    }catch(Throwable $exception){if(db()->inTransaction())db()->rollBack();$error='The customer assignment could not be saved.';}}
}

$locations=active_locations();
$locationRegions=[];foreach($locations as $location){$key=(string)($location['region_code']?:$location['region_name']);$locationRegions[$key]=(string)$location['region_name'];}asort($locationRegions);
$destinations=db()->query('SELECT id,destination_name FROM destinations WHERE is_active=1 ORDER BY destination_name')->fetchAll();
$vendors=db()->query('SELECT id,vendor_name,phone FROM vendors WHERE is_active=1 ORDER BY vendor_name')->fetchAll();
foreach($vendors as &$vendorOption){$vendorOption['vendor_name']=implode(' · ',array_filter([(string)$vendorOption['vendor_name'],(string)($vendorOption['phone']??'')]));}unset($vendorOption);
$sql="SELECT dv.id,'legacy' AS record_source,dv.company_name,dv.owner_name,dv.phone,dv.area,dv.created_at,d.destination_name,l.region_name,l.mmda_name AS district_name,l.town_name,u.full_name AS recorded_by FROM destination_visits dv INNER JOIN destinations d ON d.id=dv.destination_id LEFT JOIN locations l ON l.id=dv.location_id LEFT JOIN users u ON u.id=dv.recorded_by_user_id WHERE dv.visit_type='registration' AND dv.record_status='completed' AND dv.vendor_id IS NULL";$params=[];
if($locationId){$sql.=' AND dv.location_id=?';$params[]=$locationId;}if($destinationId){$sql.=' AND dv.destination_id=?';$params[]=$destinationId;}$sql.=' ORDER BY dv.created_at DESC,dv.id DESC LIMIT 500';$statement=db()->prepare($sql);$statement->execute($params);$customers=$statement->fetchAll();
$normalizedSql="SELECT c.id,'normalized' AS record_source,p.business_name AS company_name,c.customer_name AS owner_name,c.phone,p.area,v.created_at,d.destination_name,l.region_name,l.mmda_name AS district_name,l.town_name,u.full_name AS recorded_by FROM customers c INNER JOIN visits v ON v.id=(SELECT MAX(v2.id) FROM visits v2 WHERE v2.customer_id=c.id AND v2.visit_type='registration' AND v2.record_status='completed') INNER JOIN business_locations p ON p.id=v.bus_loc_id INNER JOIN destinations d ON d.id=p.destination_id LEFT JOIN locations l ON l.id=p.location_id LEFT JOIN users u ON u.id=c.created_by_user_id WHERE c.is_active=1 AND c.record_status='completed' AND c.vendor_id IS NULL";$normalizedParams=[];
if($locationId){$normalizedSql.=' AND p.location_id=?';$normalizedParams[]=$locationId;}if($destinationId){$normalizedSql.=' AND p.destination_id=?';$normalizedParams[]=$destinationId;}$normalizedSql.=' ORDER BY v.created_at DESC,c.id DESC LIMIT 500';$normalizedStatement=db()->prepare($normalizedSql);$normalizedStatement->execute($normalizedParams);$customers=array_merge($customers,$normalizedStatement->fetchAll());usort($customers,static fn(array $a,array $b):int=>strcmp((string)$b['created_at'],(string)$a['created_at']));$customers=array_slice($customers,0,500);
require_once __DIR__.'/../includes/header.php';
?>
<section class="management-panel"><div class="management-heading"><div><span class="section-kicker">Admin</span><h1>Assign Existing Customers</h1><p>Assign a vendor to any customer that was saved without one.</p></div><div class="management-icon"><i class="fa-solid fa-user-tag"></i></div></div><?php if($message):?><div class="profile-message is-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="profile-message is-error"><?=e($error)?></div><?php endif;?></section>
<?php $selectedLocationRegion='';foreach($locations as $location){if($locationId===(int)$location['id']){$selectedLocationRegion=(string)($location['region_code']?:$location['region_name']);break;}} ?>
<section class="management-panel"><form class="record-form" method="get"><div class="form-grid"><div class="form-field"><label for="assignment_region">Region</label><select id="assignment_region" data-location-region-select data-popup-select data-popup-search><option value="">All regions</option><?php foreach($locationRegions as $regionKey=>$regionName):?><option value="<?=e((string)$regionKey)?>" <?=$selectedLocationRegion===(string)$regionKey?'selected':''?>><?=e($regionName)?></option><?php endforeach;?></select></div><div class="form-field"><label for="location_id">Town</label><select id="location_id" name="location_id" data-location-town-select data-popup-select data-popup-search><option value="">All towns</option><?php foreach($locations as $location):?><option value="<?=(int)$location['id']?>" data-region-key="<?=e((string)($location['region_code']?:$location['region_name']))?>" data-mmda-name="<?=e((string)$location['mmda_name'])?>" <?=$locationId===(int)$location['id']?'selected':''?>><?=e((string)$location['town_name'])?></option><?php endforeach;?></select><small data-location-mmda-output></small></div><div class="form-field"><label for="destination_id">Destination</label><select id="destination_id" name="destination_id" data-popup-select data-popup-search><option value="">All destinations</option><?php foreach($destinations as $destination):?><option value="<?=(int)$destination['id']?>" <?=$destinationId===(int)$destination['id']?'selected':''?>><?=e((string)$destination['destination_name'])?></option><?php endforeach;?></select></div></div><div class="form-actions"><button class="secondary-button"><i class="fa-solid fa-filter"></i><span>Apply filters</span></button></div></form></section>
<section class="management-panel management-panel--table"><div class="management-heading management-heading--compact"><div><span class="section-kicker">Unassigned</span><h2><?=number_format(count($customers))?> customer<?=count($customers)===1?'':'s'?></h2><p>Choose customers, then select the vendor who should receive them.</p></div></div><?php if(!$customers):?><p class="empty-state">No unassigned customers match these filters.</p><?php else:?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="form-grid"><div class="form-field"><label for="customer_assignment_vendor">Assign selected customers to</label><select id="customer_assignment_vendor" name="vendor_id" data-popup-select data-popup-search required><option value="">Select vendor</option><?php foreach($vendors as $vendor):?><option value="<?=(int)$vendor['id']?>"><?=e((string)$vendor['vendor_name'])?></option><?php endforeach;?></select></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th><label class="sr-only" for="select_all_customers">Select all customers</label><input id="select_all_customers" type="checkbox" data-select-all-customers></th><th>Customer</th><th>Destination</th><th>Location</th><th>Added by</th><th>Date</th></tr></thead><tbody><?php foreach($customers as $customer):?><tr><td><input type="checkbox" name="customer_records[]" value="<?=e((string)$customer['record_source'].':'.(int)$customer['id'])?>" data-customer-assignment-checkbox></td><td><strong><?=e((string)($customer['company_name']?:$customer['owner_name']?:'Customer'))?></strong><span class="muted-text"><?=e((string)($customer['owner_name']??''))?> <?=e((string)($customer['phone']??''))?></span></td><td><?=e((string)$customer['destination_name'])?></td><td><?=e(implode(', ',array_filter([(string)($customer['town_name']??''),(string)($customer['district_name']??''),(string)($customer['region_name']??'')])))?></td><td><?=e((string)($customer['recorded_by']??''))?></td><td><?=e(date('d M Y',strtotime((string)$customer['created_at'])))?></td></tr><?php endforeach;?></tbody></table></div><div class="form-actions"><button class="login-button"><i class="fa-solid fa-user-tag"></i><span>Assign selected customers</span></button></div></form><?php endif;?></section>
<?php require_once __DIR__.'/../includes/footer.php';?>
