<?php
require_once __DIR__.'/../config/app.php';
require_once __DIR__.'/../config/simple-pdf.php';
require_module_access('pos');ensure_pos_sales_schema();
$saleId=max(0,(int)($_GET['id']??0));
$statement=db()->prepare("SELECT s.*,s.customer_name receipt_customer_name,s.customer_phone receipt_customer_phone,s.area receipt_area,l.town_name,l.region_name,u.full_name recorded_by,u.role recorder_role,v.id recorder_vendor_id,v.vendor_name recorder_vendor_name,v.phone recorder_vendor_phone,v.email recorder_vendor_email,v.area recorder_vendor_area,vl.town_name recorder_vendor_town,vl.region_name recorder_vendor_region FROM pos_sales s LEFT JOIN locations l ON l.id=s.location_id LEFT JOIN users u ON u.id=s.recorded_by_user_id LEFT JOIN vendors v ON v.user_id=s.recorded_by_user_id LEFT JOIN locations vl ON vl.id=v.location_id WHERE s.id=? LIMIT 1");
$statement->execute([$saleId]);$sale=$statement->fetch();if(!$sale){http_response_code(404);exit('Receipt not found.');}
$personnel=current_vendor_personnel();$vendor=current_vendor_profile();$canViewVendorSales=current_user_role()==='vendor'||($personnel&&(int)($personnel['can_reports']??0)===1);$canView=is_admin_user()||(int)$sale['recorded_by_user_id']===(int)current_user_id()||($canViewVendorSales&&$vendor&&(int)($sale['vendor_id']??0)===(int)$vendor['id']);if(!$canView){http_response_code(404);exit('Receipt not found.');}
$itemsStatement=db()->prepare('SELECT * FROM pos_sale_items WHERE sale_id=? ORDER BY id');$itemsStatement->execute([$saleId]);$items=$itemsStatement->fetchAll();
$vins=[];if($items){$ids=array_map('intval',array_column($items,'id'));$marks=implode(',',array_fill(0,count($ids),'?'));$vinStatement=db()->prepare("SELECT sale_item_id,vin_number FROM pos_sale_vins WHERE sale_item_id IN ($marks) ORDER BY id");$vinStatement->execute($ids);foreach($vinStatement->fetchAll() as $row)$vins[(int)$row['sale_item_id']][]=(string)$row['vin_number'];}
$total=$items?array_sum(array_map(static fn(array $item):float=>(float)$item['total_amount'],$items)):(float)$sale['subtotal'];$isVendor=(string)($sale['recorder_role']??'')==='vendor'&&(int)($sale['recorder_vendor_id']??0)>0;$issuer=$isVendor?(string)$sale['recorder_vendor_name']:COMPANY_NAME;$phone=$isVendor?trim((string)($sale['recorder_vendor_phone']??'')):'';$email=$isVendor?trim((string)($sale['recorder_vendor_email']??'')):'';$address=$isVendor?implode(', ',array_filter([(string)($sale['recorder_vendor_area']??''),(string)($sale['recorder_vendor_town']??''),(string)($sale['recorder_vendor_region']??'')])):'';$customerLocation=implode(', ',array_filter([(string)($sale['receipt_area']??''),(string)($sale['town_name']??''),(string)($sale['region_name']??'')]));
$pdf=new SimpleReceiptPdf();$left=46;$right=549;$top=50;
$logoPath=__DIR__.'/../assets/images/autoplus-logo-receipt.jpg';
$drawHeader=function()use($pdf,$issuer,$address,$phone,$email,$sale,$left,$right,$logoPath):float{$pdf->rect(0,0,595.28,9,'187b6d');$pdf->jpeg($logoPath,$left,34,84,53);$pdf->text(143,48,$issuer,17,true,'123a60');$line=66;foreach(array_filter([$address,$phone!==''?'Phone: '.$phone:'',$email]) as $detail){$pdf->text(143,$line,$detail,8,false,'60748a');$line+=11;}$pdf->text(455,52,'SALES RECEIPT',11,true,'187b6d');$pdf->text(455,70,(string)$sale['sale_ref'],9,true,'123a60');$pdf->line($left,104,$right,104,'bdd0df',1);return 126;};
$top=$drawHeader();$pdf->text($left,$top,'BILL TO',7,true,'187b6d');$pdf->text($left,$top+18,(string)$sale['receipt_customer_name'],11,true);if((string)($sale['receipt_customer_phone']??'')!=='')$pdf->text($left,$top+34,(string)$sale['receipt_customer_phone'],8,false,'60748a');if($customerLocation!=='')$pdf->text($left,$top+47,$customerLocation,8,false,'60748a');$pdf->text(420,$top,'DATE',7,true,'187b6d');$pdf->text(420,$top+18,date('j M Y',strtotime((string)$sale['sale_date'])),9,true);$top+=78;
$drawColumns=function(float $y)use($pdf,$left,$right):void{$pdf->rect($left,$y,$right-$left,27,'edf4f8');$pdf->text($left+10,$y+18,'DESCRIPTION',7,true,'476276');$pdf->text(370,$y+18,'QTY',7,true,'476276');$pdf->text(420,$y+18,'UNIT',7,true,'476276');$pdf->text(492,$y+18,'AMOUNT',7,true,'476276');};$drawColumns($top);$top+=42;
foreach($items as $item){$hasVin=!empty($vins[(int)$item['id']]);$height=$hasVin?42:29;if($top+$height>760){$pdf->newPage();$top=$drawHeader();$drawColumns($top);$top+=42;}$pdf->text($left+10,$top,trim((string)$item['brand_name'].' '.(string)$item['plug_number']),9,true);if($hasVin)$pdf->text($left+10,$top+15,'VIN: '.implode(', ',$vins[(int)$item['id']]),7,false,'60748a');$pdf->text(378,$top,(string)(int)$item['quantity'],9);$pdf->text(420,$top,number_format((float)$item['unit_price'],2),9);$pdf->text(492,$top,number_format((float)$item['total_amount'],2),9,true);$pdf->line($left,$top+$height-8,$right,$top+$height-8);$top+=$height;}
if(!$items){$pdf->text($left+10,$top,'Item details are not available for this sale.',9,false,'60748a');$top+=35;}$top+=10;$pdf->rect(356,$top,193,44,'edf7f4');$pdf->text(372,$top+27,'TOTAL',9,true,'187b6d');$pdf->text(455,$top+27,'GHS '.number_format($total,2),12,true,'123a60');$top+=78;$pdf->line($left,$top,$right,$top,'bdd0df');$pdf->text($left,$top+24,'Thank you for your purchase.',10,true,'187b6d');$pdf->text($left,$top+42,'Recorded by '.((string)($sale['recorded_by']?:'System')).' - '.date('d M Y H:i',strtotime((string)$sale['created_at'])),7,false,'60748a');
$filename=preg_replace('/[^A-Za-z0-9_-]+/','-',(string)$sale['sale_ref']).'-receipt.pdf';header('Content-Type: application/pdf');header('Content-Disposition: '.((string)($_GET['download']??'')==='1'?'attachment':'inline').'; filename="'.$filename.'"');header('Cache-Control: private, no-store');echo $pdf->output();
