<?php
require_once __DIR__ . '/../config/app.php';
require_menu_item_access('setup_commissions');
ensure_pos_sales_schema();

$pageTitle='Plug Commission Setup';
$breadcrumbs=[['label'=>'Home','url'=>app_url('index.php')],['label'=>'Admin','url'=>app_url('admin.php')],['label'=>'Setup','url'=>app_url('setup.php')],['label'=>'Plug Commissions']];
$internalBackUrl=requested_return_url(app_url('pos.php?view=setup'));
$message='';$error='';$editId=max(0,(int)($_GET['edit']??0));
$form=['brand_name'=>'','spark_plug_id'=>'','vendor_id'=>'','discount_percentage'=>'20.00','effective_from'=>date('Y-m-d'),'effective_to'=>'','is_active'=>'1'];
if($editId){$edit=db()->prepare('SELECT d.*,sp.brand_name FROM plug_commissions d INNER JOIN spark_plugs sp ON sp.id=d.spark_plug_id WHERE d.id=?');$edit->execute([$editId]);if($row=$edit->fetch())$form=['brand_name'=>(string)$row['brand_name'],'spark_plug_id'=>(string)$row['spark_plug_id'],'vendor_id'=>(string)($row['vendor_id']??''),'discount_percentage'=>(string)$row['commission_percentage'],'effective_from'=>(string)$row['effective_from'],'effective_to'=>(string)($row['effective_to']??''),'is_active'=>(string)(int)$row['is_active']];else $editId=0;}
if($_SERVER['REQUEST_METHOD']==='POST'){
    $editId=max(0,(int)($_POST['discount_id']??0));
    $postedPlugSelection=(string)($_POST['spark_plug_id']??'');
    if((int)$postedPlugSelection<=0&&trim((string)($_POST['brand_name']??''))!=='')$editId=0;
    $form=['brand_name'=>trim((string)($_POST['brand_name']??'')),'spark_plug_id'=>in_array($postedPlugSelection,['all','-1'],true)?'-1':(string)max(0,(int)$postedPlugSelection),'vendor_id'=>(string)max(0,(int)($_POST['vendor_id']??0)),'discount_percentage'=>trim((string)($_POST['discount_percentage']??'')),'effective_from'=>trim((string)($_POST['effective_from']??'')),'effective_to'=>trim((string)($_POST['effective_to']??'')),'is_active'=>(string)($_POST['is_active']??'1')];
    if(!verify_csrf_token((string)($_POST['csrf_token']??'')))$error='Your session expired. Please try again.';
    else{
        $allPlugs=(int)$form['spark_plug_id']<=0&&$form['brand_name']!=='';
        if($allPlugs){$plugCheck=db()->prepare('SELECT id,brand_name,plug_number FROM spark_plugs WHERE brand_name=? AND is_active=1 ORDER BY plug_number');$plugCheck->execute([$form['brand_name']]);$targetPlugs=$plugCheck->fetchAll();}
        else{$plugCheck=db()->prepare('SELECT id,brand_name,plug_number FROM spark_plugs WHERE id=? AND brand_name=? AND is_active=1');$plugCheck->execute([(int)$form['spark_plug_id'],$form['brand_name']]);$plug=$plugCheck->fetch();$targetPlugs=$plug?[$plug]:[];}
        $percentage=(float)$form['discount_percentage'];
        if(!$targetPlugs)$error='Select a valid brand and plug number.';
        elseif($percentage<0||$percentage>100)$error='Commission percentage must be between 0 and 100.';
        elseif(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$form['effective_from']))$error='Select a valid effective-from date.';
        elseif($form['effective_to']!==''&&(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$form['effective_to'])||$form['effective_to']<$form['effective_from']))$error='The effective-to date must be on or after the effective-from date.';
        else{
            try{
                $vendorId=(int)$form['vendor_id']?:null;
                if($vendorId){$vendorCheck=db()->prepare("SELECT COUNT(*) FROM vendors WHERE id=? AND vendor_type='sor' AND is_active=1");$vendorCheck->execute([$vendorId]);if(!(int)$vendorCheck->fetchColumn())throw new DomainException('Select a valid active SoR vendor.');}
                db()->beginTransaction();
                if(!$editId&&$form['is_active']!=='0'){$closePrevious=db()->prepare('UPDATE plug_commissions SET effective_to=? WHERE spark_plug_id=? AND ((vendor_id IS NULL AND ? IS NULL) OR vendor_id=?) AND is_active=1 AND effective_from<? AND (effective_to IS NULL OR effective_to>=?)');$previousDay=date('Y-m-d',strtotime($form['effective_from'].' -1 day'));foreach($targetPlugs as $targetPlug)$closePrevious->execute([$previousDay,(int)$targetPlug['id'],$vendorId,$vendorId,$form['effective_from'],$form['effective_from']]);}
                $overlap=db()->prepare('SELECT COUNT(*) FROM plug_commissions WHERE spark_plug_id=? AND ((vendor_id IS NULL AND ? IS NULL) OR vendor_id=?) AND is_active=1 AND id<>? AND effective_from<=COALESCE(?,\'9999-12-31\') AND COALESCE(effective_to,\'9999-12-31\')>=?');
                foreach($targetPlugs as $targetPlug){$overlap->execute([(int)$targetPlug['id'],$vendorId,$vendorId,$editId,$form['effective_to']?:null,$form['effective_from']]);if((int)$overlap->fetchColumn())throw new DomainException($targetPlug['brand_name'].' '.$targetPlug['plug_number'].' already has an active commission rule overlapping those dates for the selected vendor scope.');}
                if($editId){$targetPlug=$targetPlugs[0];$values=[(int)$targetPlug['id'],$vendorId,$percentage,$form['effective_from'],$form['effective_to']?:null,$form['is_active']==='0'?0:1,$editId];db()->prepare('UPDATE plug_commissions SET spark_plug_id=?,vendor_id=?,commission_percentage=?,effective_from=?,effective_to=?,is_active=? WHERE id=?')->execute($values);$message='Plug commission updated successfully.';}
                else{$insert=db()->prepare('INSERT INTO plug_commissions(spark_plug_id,vendor_id,commission_percentage,effective_from,effective_to,is_active,created_by_user_id) VALUES(?,?,?,?,?,?,?)');foreach($targetPlugs as $targetPlug)$insert->execute([(int)$targetPlug['id'],$vendorId,$percentage,$form['effective_from'],$form['effective_to']?:null,$form['is_active']==='0'?0:1,current_user_id()]);$message=$allPlugs?count($targetPlugs).' plug commission rules added successfully.':'Plug commission added successfully.';}
                db()->commit();
                $editId=0;$form=['brand_name'=>'','spark_plug_id'=>'','vendor_id'=>'','discount_percentage'=>'20.00','effective_from'=>date('Y-m-d'),'effective_to'=>'','is_active'=>'1'];
            }catch(Throwable $exception){if(db()->inTransaction())db()->rollBack();$error=$exception instanceof DomainException?$exception->getMessage():'The commission could not be saved.';}
        }
    }
}
$brands=db()->query("SELECT DISTINCT brand_name FROM spark_plugs WHERE is_active=1 ORDER BY brand_name")->fetchAll();
$plugRows=db()->query("SELECT id,brand_name,plug_number FROM spark_plugs WHERE is_active=1 ORDER BY brand_name,plug_number")->fetchAll();
$plugs=[];$lastPlugBrand=null;foreach($plugRows as $plugRow){if($lastPlugBrand!==$plugRow['brand_name']){$plugs[]=['id'=>-1,'brand_name'=>$plugRow['brand_name'],'plug_number'=>'All plug numbers'];$lastPlugBrand=$plugRow['brand_name'];}$plugs[]=$plugRow;}
$vendors=db()->query("SELECT id,vendor_name FROM vendors WHERE vendor_type='sor' AND is_active=1 ORDER BY vendor_name")->fetchAll();
$discounts=db()->query("SELECT d.id,d.commission_percentage AS discount_percentage,d.effective_from,d.effective_to,d.is_active,d.created_at,sp.brand_name,sp.plug_number,v.vendor_name FROM plug_commissions d INNER JOIN spark_plugs sp ON sp.id=d.spark_plug_id LEFT JOIN vendors v ON v.id=d.vendor_id ORDER BY sp.brand_name,sp.plug_number,v.vendor_name,d.effective_from DESC")->fetchAll();
require_once __DIR__ . '/../includes/header.php';
?>
<section class="management-panel"><div class="management-heading"><div><span class="section-kicker">POS Setup</span><h1>Plug Commissions</h1><p>Schedule default or vendor-specific SoR commission percentages. Vendor rules take priority over the default rule for the same plug and sale date.</p></div><div class="management-icon"><i class="fa-solid fa-percent"></i></div></div>
<?php if($message):?><div class="profile-message is-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="profile-message is-error"><?=e($error)?></div><?php endif;?>
<form class="record-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="discount_id" value="<?=$editId?>"><div class="form-grid"><div class="form-field"><label for="discount_brand">Brand</label><select id="discount_brand" name="brand_name" data-popup-select data-popup-search data-popup-hide-empty required><option value="">Search or select brand</option><?php foreach($brands as $brand):?><option value="<?=e((string)$brand['brand_name'])?>" <?=$form['brand_name']===(string)$brand['brand_name']?'selected':''?>><?=e((string)$brand['brand_name'])?></option><?php endforeach;?></select></div><div class="form-field"><label for="discount_plug">Plug number</label><select id="discount_plug" name="spark_plug_id" data-popup-select data-popup-search data-popup-hide-empty required><option value="">Search or select plug number</option><?php foreach($plugs as $plug):?><option value="<?=(int)$plug['id']?>" data-brand="<?=e((string)$plug['brand_name'])?>" <?=$form['spark_plug_id']===(string)$plug['id']?'selected':''?>><?=e((string)$plug['plug_number'])?></option><?php endforeach;?></select></div><div class="form-field"><label for="commission_vendor">SoR vendor</label><select id="commission_vendor" name="vendor_id" data-popup-select data-popup-search><option value="">All SoR vendors (default)</option><?php foreach($vendors as $vendor):?><option value="<?=(int)$vendor['id']?>" <?=$form['vendor_id']===(string)$vendor['id']?'selected':''?>><?=e((string)$vendor['vendor_name'])?></option><?php endforeach;?></select></div><div class="form-field"><label for="discount_percentage">Commission (%)</label><input id="discount_percentage" name="discount_percentage" type="number" min="0" max="100" step="0.01" value="<?=e($form['discount_percentage'])?>" required></div><div class="form-field"><label for="effective_from">Effective from</label><input id="effective_from" name="effective_from" type="date" value="<?=e($form['effective_from'])?>" required></div><div class="form-field"><label for="effective_to">Effective to (optional)</label><input id="effective_to" name="effective_to" type="date" value="<?=e($form['effective_to'])?>"></div><div class="form-field"><label for="discount_status">Status</label><select id="discount_status" name="is_active"><option value="1" <?=$form['is_active']==='1'?'selected':''?>>Active</option><option value="0" <?=$form['is_active']==='0'?'selected':''?>>Inactive</option></select></div></div><div class="form-actions"><button class="login-button"><i class="fa-solid fa-floppy-disk"></i><span><?=$editId?'Update Commission':'Save Commission'?></span></button><?php if($editId):?><a class="secondary-button" href="<?=e(app_url('pos-discount-setup.php'))?>">Cancel</a><?php endif;?></div></form></section>
<section class="management-panel management-panel--table"><div class="management-heading management-heading--compact"><div><span class="section-kicker">Current Rules</span><h2>SoR Commission Schedule</h2></div></div><?php if(!$discounts):?><p class="empty-state">No plug commissions have been added.</p><?php else:?><div class="table-wrap"><table class="data-table data-table--compact"><thead><tr><th>Brand</th><th>Plug Number</th><th>Vendor Scope</th><th>Commission</th><th>Effective Period</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($discounts as $discount):?><tr><td><?=e((string)$discount['brand_name'])?></td><td><?=e((string)$discount['plug_number'])?></td><td><?=e((string)($discount['vendor_name']?:'All SoR vendors'))?></td><td><?=e(number_format((float)$discount['discount_percentage'],2))?>%</td><td><?=e(date('d M Y',strtotime((string)$discount['effective_from'])))?> – <?=e($discount['effective_to']?date('d M Y',strtotime((string)$discount['effective_to'])):'Ongoing')?></td><td><span class="status-badge <?=(int)$discount['is_active']?'is-active':'is-inactive'?>"><?=(int)$discount['is_active']?'Active':'Inactive'?></span></td><td><a class="action-button" href="<?=e(app_url('pos-discount-setup.php?edit='.(int)$discount['id']))?>"><i class="fa-solid fa-pen"></i><span>Edit</span></a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<script>document.addEventListener('DOMContentLoaded',function(){const brand=document.querySelector('#discount_brand');const plug=document.querySelector('#discount_plug');const options=Array.from(plug?.options||[]);const sync=function(){const value=brand?.value||'';if(plug)plug.value='';options.forEach(function(option){if(!option.value)return;const match=value!==''&&option.dataset.brand===value;option.hidden=!match;option.disabled=!match;});if(typeof updateLookupButton==='function'&&plug)updateLookupButton(plug);};brand?.addEventListener('change',sync);if(brand?.value){const selected='<?=e($form['spark_plug_id'])?>';options.forEach(function(option){if(!option.value)return;const match=option.dataset.brand===brand.value;option.hidden=!match;option.disabled=!match;});if(plug)plug.value=selected;}else sync();});</script>
<?php require_once __DIR__ . '/../includes/footer.php';?>
