<?php
require_once __DIR__ . '/../config/app.php';
require_module_access('admin');
ensure_destination_visit_schema();
$pageTitle='Shop Type Setup'; $breadcrumbs=[['label'=>'Home','url'=>app_url('index.php')],['label'=>'Admin','url'=>app_url('admin.php')],['label'=>'Setup','url'=>app_url('setup.php')],['label'=>'Shop Type Setup']]; $message=$error=''; $editId=max(0,(int)($_GET['edit']??0)); $name=''; $status='1';
if($editId){$s=db()->prepare('SELECT * FROM shop_types WHERE id=?');$s->execute([$editId]);$r=$s->fetch();if($r){$name=(string)$r['shop_type_name'];$status=(string)(int)$r['is_active'];}else{$editId=0;}}
if($_SERVER['REQUEST_METHOD']==='POST'){$name=trim((string)($_POST['shop_type_name']??''));$status=(string)($_POST['status']??'1');$id=max(0,(int)($_POST['shop_type_id']??0));$action=(string)($_POST['form_action']??'save');if(!verify_csrf_token((string)($_POST['csrf_token']??''))){$error='Your session expired. Please try again.';}elseif($action==='delete'&&$id){try{db()->prepare('DELETE FROM shop_types WHERE id=?')->execute([$id]);$message='Shop type deleted successfully.';}catch(PDOException $e){$error='This shop type is already used and cannot be deleted.';}}elseif($name===''){$error='Shop type name is required.';}else{try{if($id){db()->prepare('UPDATE shop_types SET shop_type_name=?,is_active=? WHERE id=?')->execute([$name,$status==='0'?0:1,$id]);$message='Shop type updated successfully.';}else{db()->prepare('INSERT INTO shop_types (shop_type_name,is_active) VALUES (?,?)')->execute([$name,$status==='0'?0:1]);$message='Shop type added successfully.';}$name='';$status='1';$editId=0;}catch(PDOException $e){$error='That shop type already exists.';}}}
$rows=db()->query('SELECT * FROM shop_types ORDER BY shop_type_name')->fetchAll(); require_once __DIR__.'/../includes/header.php';
?>
<section class="management-panel"><div class="management-heading"><div><span class="section-kicker">Setup</span><h1>Shop Type Setup</h1><p>Manage the Shop Type choices used for Shop destination visits.</p></div><div class="management-icon"><i class="fa-solid fa-store"></i></div></div><?php if($message):?><div class="profile-message is-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="profile-message is-error"><?=e($error)?></div><?php endif;?><form class="record-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="form_action" value="save"><input type="hidden" name="shop_type_id" value="<?=$editId?>"><div class="form-grid"><div class="form-field"><label for="shop_type_name">Shop type</label><input id="shop_type_name" name="shop_type_name" value="<?=e($name)?>" required></div><div class="form-field"><label for="status">Status</label><select id="status" name="status"><option value="1" <?=$status==='1'?'selected':''?>>Active</option><option value="0" <?=$status==='0'?'selected':''?>>Inactive</option></select></div></div><div class="form-actions"><button class="login-button"><?= $editId?'Update':'Save' ?> shop type</button><?php if($editId):?><a class="secondary-button" href="<?=e(app_url('shop-type-setup.php'))?>">Cancel</a><?php endif;?></div></form></section>
<section class="management-panel management-panel--table"><div class="management-heading management-heading--compact"><div><h2>Shop Types</h2></div></div><?php if(!$rows):?><p class="empty-state">No shop types added yet.</p><?php else:?><div class="table-wrap"><table class="data-table data-table--compact"><thead><tr><th>Shop Type</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e((string)$r['shop_type_name'])?></td><td><span class="status-badge <?=$r['is_active']?'is-active':'is-inactive'?>"><?=$r['is_active']?'Active':'Inactive'?></span></td><td><div class="table-actions"><a class="action-button" href="<?=e(app_url('shop-type-setup.php?edit='.(int)$r['id']))?>">Edit</a><form method="post" data-confirm-title="Delete shop type?"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="form_action" value="delete"><input type="hidden" name="shop_type_id" value="<?=(int)$r['id']?>"><button class="action-button is-danger">Delete</button></form></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php require_once __DIR__.'/../includes/footer.php';?>
